"""One-off generator: parse seeded INSERT rows out of accounting_db.sql and emit
``database/seed_data.py`` as plain Python literals. Run from the repo root:

    python database/_gen_seed_data.py
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SQL = (ROOT / "accounting_db.sql").read_text(encoding="utf-8")

TABLES = [
    ("account_types", ["id", "code", "name_th", "name_en", "normal_balance", "fs_section"]),
    ("accounts", ["id", "company_id", "account_type_id", "parent_id", "code", "name_th", "name_en", "level", "is_header", "is_active", "created_at"]),
    ("companies", ["id", "code", "name_th", "name_en", "tax_id", "registered_no", "address", "phone", "email", "logo_url", "fiscal_year_start", "base_currency", "is_active", "created_at", "updated_at"]),
    ("currencies", ["code", "name", "symbol"]),
    ("permissions", ["id", "module", "action", "description"]),
    ("roles", ["id", "company_id", "code", "name", "description", "is_system", "created_at"]),
    ("role_permissions", ["role_id", "permission_id"]),
    ("units_of_measure", ["id", "company_id", "code", "name_th"]),
    ("users", ["id", "username", "email", "password_hash", "full_name", "employee_code", "is_active", "last_login_at", "created_at", "updated_at"]),
    ("user_company_access", ["id", "user_id", "company_id", "branch_id", "department_id", "role_id", "is_default"]),
    ("vat_rates", ["id", "code", "name_th", "name_en", "rate", "vat_category", "effective_from", "effective_until", "output_vat_account_id", "input_vat_account_id", "is_active"]),
    ("wht_types", ["id", "code", "section", "description_th", "description_en", "default_rate", "reduced_rate", "form_type", "is_active"]),
]


def extract_values_block(table: str) -> str:
    # Grab everything between "INSERT INTO `table` (...) VALUES" and the closing ";"
    m = re.search(r"INSERT INTO `" + re.escape(table) + r"`[^;]*?VALUES\s*(.*?);", SQL, re.S)
    if not m:
        raise ValueError(f"no INSERT found for {table}")
    return m.group(1)


def split_tuples(block: str):
    """Yield each top-level (...) tuple string, respecting quotes/escapes."""
    depth = 0
    in_str = False
    esc = False
    buf = []
    for ch in block:
        if in_str:
            buf.append(ch)
            if esc:
                esc = False
            elif ch == "\\":
                esc = True
            elif ch == "'":
                in_str = False
            continue
        if ch == "'":
            in_str = True
            buf.append(ch)
        elif ch == "(":
            if depth == 0:
                buf = []
            else:
                buf.append(ch)
            depth += 1
        elif ch == ")":
            depth -= 1
            if depth == 0:
                yield "".join(buf)
            else:
                buf.append(ch)
        else:
            if depth > 0:
                buf.append(ch)


def split_fields(tup: str):
    """Split a tuple body on top-level commas, respecting quotes/escapes."""
    out = []
    in_str = False
    esc = False
    buf = []
    for ch in tup:
        if in_str:
            buf.append(ch)
            if esc:
                esc = False
            elif ch == "\\":
                esc = True
            elif ch == "'":
                in_str = False
            continue
        if ch == "'":
            in_str = True
            buf.append(ch)
        elif ch == ",":
            out.append("".join(buf).strip())
            buf = []
        else:
            buf.append(ch)
    out.append("".join(buf).strip())
    return out


def parse_value(raw: str):
    if raw.upper() == "NULL":
        return None
    if raw.startswith("'") and raw.endswith("'"):
        s = raw[1:-1]
        s = s.replace("\\'", "'").replace('\\"', '"').replace("\\\\", "\\")
        return s
    # number
    if re.fullmatch(r"-?\d+", raw):
        return int(raw)
    return float(raw)


def build():
    data = {}
    for table, cols in TABLES:
        block = extract_values_block(table)
        rows = []
        for tup in split_tuples(block):
            vals = [parse_value(v) for v in split_fields(tup)]
            assert len(vals) == len(cols), f"{table}: {len(vals)} vals != {len(cols)} cols\n{tup}"
            rows.append(dict(zip(cols, vals)))
        data[table] = rows
    return data


def emit(data):
    import pprint
    lines = [
        '"""Seed data parsed from accounting_db.sql. Generated by _gen_seed_data.py.',
        "",
        "Integer ids/foreign keys are kept as-is here; database/seed.py maps them to",
        "deterministic UUIDs at insert time.",
        '"""',
        "",
    ]
    for table, _ in TABLES:
        lines.append(f"{table.upper()} = " + pprint.pformat(data[table], width=120, sort_dicts=False))
        lines.append("")
    (ROOT / "database" / "seed_data.py").write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    d = build()
    for t, _ in TABLES:
        print(f"{t}: {len(d[t])} rows")
    emit(d)
    print("wrote database/seed_data.py")
